assembler:	assembler.c 
	gcc -g -ansi -pedantic -Wall assembler.c pre_assemb.c macros_expand.c macros_help.c first_pass.c passes_help.c guidance_help.c instructions_help.c second_pass.c print.c -o assembler -lm 
